CREATE ROLE g_bill_daemon_local NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
CREATE ROLE g_bill_daemon_remote  NOSUPERUSER NOINHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;

CREATE ROLE bill_daemon_local LOGIN
  ENCRYPTED PASSWORD 'md50b11a11686f194f92e10fa9eb342771c'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
    GRANT g_bill_daemon_local TO bill_daemon_local;
    
CREATE ROLE bill_daemon_remote LOGIN
  ENCRYPTED PASSWORD 'md5169bc1d8d25a7a91c4e7e2e671631012'
    NOSUPERUSER INHERIT NOCREATEDB NOCREATEROLE NOREPLICATION;
    GRANT g_bill_daemon_remote TO bill_daemon_remote;
    